name: eslint

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - name: Install Node.js
        env:
          NODE_VERSION: 18.14.1
        run: nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: List source code with ESLint
        run: npm run lint